### ISSUE TITLE
broken links in documentation

### ISSUE THREAD

**Issue by gemmaro** [nozaq/shogi-rs#29]
There are some broken links in crate documentation.

* [shogi](https://nozaq.github.io/shogi-rs/shogi/index.html)
  * http://www.geocities.jp/shogidokoro/usi.html
* [Bitboard](https://nozaq.github.io/shogi-rs/shogi/bitboard/struct.Bitboard.html)
  * http://chessprogramming.wikispaces.com/BMI2#PEXTBitboards
  * http://chessprogramming.wikispaces.com/BMI2
* [TimeControl](https://nozaq.github.io/shogi-rs/shogi/time/enum.TimeControl.html)
  * https://en.wikipedia.org/wiki/Time_control#Japanese_byo-yomi (URI id doesn't work)
  * https://en.wikipedia.org/wiki/Time_control#Compensation_.28delay_or_increment_methods.29 (URI id doesn't work)

**Comment by nozaq** [comment]
@gemmaro Thank you for your report. Just merged #30 into master 🎉
